### ISSUE TITLE
Tic tac toe Game 

### ISSUE THREAD

**Issue by vaishh29** [Mozilla-Campus-Club-Cummins/Spring-of-Code#100]
Create the Tic tac toe game using Android Studio, Java/Kotlin and XML

**Comment by vaishnavi-3969** [comment]
C22020881923
T.Y.Comp.
Interested in working on this :)

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake.
I would like to work on this issue.

**Comment by vaishh29** [comment]
> Piyusha Ghodake. I would like to work on this issue.

Please register to Spring of Code through the link in the mail and then comment again once done.

**Comment by PiyushaGhodake** [comment]
Yes done.

**Comment by vaishh29** [comment]
> Yes done.

Please check if your previous pull request has been merged or not, only when it is merged I can assign you this issue. 
Talk/Comment to the previous issue if not merged.
When that pull request is merged , then comment on the issue again I'll assign the issue to you .

**Comment by PiyushaGhodake** [comment]
Okk.

**Comment by PiyushaGhodake** [comment]
@vaishh29 I would like to work on this issue.
Piyusha Ghodake
SY COMP

**Comment by vaishh29** [comment]
> @vaishh29 I would like to work on this issue. Piyusha Ghodake SY COMP

I have assigned you the issue. You have 2days to complete it

**Comment by PiyushaGhodake** [comment]
@vaishh29 Can u check it now whether it's right?

**Comment by PiyushaGhodake** [comment]
@vaishh29 there are 4 files mainactivity.java(named as tictactoe), strings.xml , activity_main.xml(named as adding xml file) and colors.xml(named as adding xml file).
