### ISSUE TITLE
Music Player 

### ISSUE THREAD

**Issue by vaishh29** [Mozilla-Campus-Club-Cummins/Spring-of-Code#101]
Design a Music player for Android such that user is able to play, pause, and stop a song. 

Your application should fetch all the songs from phone storage and will display it in the form of a list. It will take input from the user and search accordingly.

**Comment by sayli2003** [comment]
I would like to work on this issue
Sayli Borole
Sy comp

**Comment by vaishh29** [comment]
> I would like to work on this issue Sayli Borole Sy comp

You have been assigned the issue. You have 2 days from now to work on it.

**Comment by aditisinghal1210** [comment]
Can u pls assign me this issue. I have finished my previous issue.
Aditi singhal

**Comment by vaishh29** [comment]
@sayli2003 you were assigned this issue 3days ago. As no progress has been seen you will be unassigned for this issue.

**Comment by vaishh29** [comment]
> @vaishh29 I have opened a PR please check it out

You were a late for the deadline so I cannot merge your pull request. But you can work on other issues .

**Comment by aditisinghal1210** [comment]
Hey,I was assigned this as well as #84 3 days ago,so I have completed #84 now,I can work on this now.

**Comment by vaishh29** [comment]
> Hey,I was assigned this as well as #84 3 days ago,so I have completed #84 now,I can work on this now.

You are assigned to this issue

**Comment by vaishh29** [comment]
> Hey,I was assigned this as well as #84 3 days ago,so I have completed #84 now,I can work on this now.

Also, #84 issue was your 3rd issue you worked on right?

**Comment by vaishh29** [comment]
@aditisinghal1210 it is noticed that you are working on issue #104 as the moment so I'll unassign you from this issue. Once that issue is done please let me know I'll assign you to this issue.

**Comment by aditisinghal1210** [comment]
> > Hey,I was assigned this as well as #84 3 days ago,so I have completed #84 now,I can work on this now.
> 
> Also, #84 issue was your 3rd issue you worked on right?

It was my second.
