### ISSUE TITLE
Chinese Postman Problem

### ISSUE THREAD

**Issue by vaishh29** [Mozilla-Campus-Club-Cummins/Spring-of-Code#102]
Explain the Chinese Postman Problem.
Study different Variations in Chinese Postman Problem and describe the approaches for respective variation.

**Comment by ShreyaShetty263** [comment]
Shreya Shetty
would like to work on this issue

**Comment by ArtiHere** [comment]
I am Arti Tambade
I would like to work on this issue, could you please assign this issue to me?

**Comment by vaishh29** [comment]
> I am Arti Tambade I would like to work on this issue, could you please assign this issue to me?

I have assigned this issue to you . You have 2days to work on this issue.

**Comment by vaishh29** [comment]
@ArtiHere I will check your commit tonight and merge your request it's as expected
