### ISSUE TITLE
Social Media Sentiment Analysis Using Twitter Dataset

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#104]
Develop an NLP Twitter sentiment analysis model. Classify the tweets into positive or negative sentiments. 

Use the dataset available on the Kaggle.

**Comment by alwaystanaya20** [comment]
Vaibhavi Thakare
SY Comp
I'd love to work on this issue!

**Comment by shruti-2412** [comment]
@alwaystanaya20 you can work on single issue at a time

**Comment by Rasika-Kanitkar** [comment]
I want to work on this
Rasika Kanitkar
SY Comp(UCE2021630)

**Comment by aditisinghal1210** [comment]
I have finished my previous issue.I had requested earlier,can you pls assign me this issue?

**Comment by shruti-2412** [comment]
@aditisinghal1210 is your previous pull request merged?

**Comment by aditisinghal1210** [comment]
> @aditisinghal1210 is your previous pull request merged?

![Screenshot_20230323_145254_GitHub.jpg](https://user-images.githubusercontent.com/98580057/227158890-be3c1ece-bb07-4b95-b541-fa690d49bfd9.jpg)

Yes I hv merged the pull request. Attaching here an ss

**Comment by shruti-2412** [comment]
@aditisinghal1210 actually you have made the pull request in the main branch.
Firstly go to the solutions folder. There you will see an option to add a file on the right side. Click on that and then click on create a new file. Add your file name and copy and paste your code in the code section. And then at the end of the commit file add the issue name in the comment section mention the issue no and select the corresponding issue and click on commit the new file.

Once your previous PR is merged I will assign you this issue.

**Comment by aditisinghal1210** [comment]
> @aditisinghal1210 actually you have not made the pull request in the main branch.
> Firstly go to the solutions folder. There you will see an option to add a file on the right side. Click on that and then click on create a new file. Add your file name and copy and paste your code in the code section. And then at the end of the commit file add the issue name in the comment section mention the issue no and select the corresponding issue and click on commit the new file.
> 
> Once your previous PR is merged I will assign you this issue.

Hey ! Thanks for your help. I have created a merge request. Pls check

**Comment by shruti-2412** [comment]
@aditisinghal1210 you can start working on the issue now. You have 2 days for it. You can use any dataset available on kaggle.

**Comment by aditisinghal1210** [comment]
Hey! I finished my previous issue,can you pls assign me this one.

**Comment by shruti-2412** [comment]
@aditisinghal1210 you can start working on the issue.

**Comment by shruti-2412** [comment]
@aditisinghal1210 are you done with the solution?

**Comment by aditisinghal1210** [comment]
No. I am not done yet.
