### ISSUE TITLE
Android Application of a Quiz App

### ISSUE THREAD

**Issue by Gaurika-Gupta** [Mozilla-Campus-Club-Cummins/Spring-of-Code#116]
Design an Android Application in which any person can attempt a quiz.

The following functionalities are expected in the application:
1. User can start and attempt a quiz
2. There are 5 or more questions. 
3. There is a timer to answer each question(say 20 secs) and is visible on the screen.
4. The score is displayed at the end of the quiz.

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, could you please assign this issue to me?

**Comment by Gaurika-Gupta** [comment]
Please comment once you complete the previous issue and then I will assign you this issue.

**Comment by aarushichopkar** [comment]
I would like to work on this issue.
Aarushi Chopkar
TY ENTC

**Comment by Gaurika-Gupta** [comment]
Assigning this issue to @ArtiHere
