### ISSUE TITLE
Disarium number

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#12]
Write a program to check whether the given value is a disarium number .
 (Hint: Let the number be 175 .As,1^1+7^2+5^3=175 the number is said to be a disarium number)

**Comment by ambi-04** [comment]
Hello I would like to work on this
Ambika Deshmukh
First Year IT

**Comment by utkarshaskumbhar** [comment]
i am utkarsha kumbhar
please assign me this issue

**Comment by Sannidhi26** [comment]
I am sannidhi nandgaonkar
I have completed my 1st issue. can you please assign me this issue?
Sy comp

**Comment by Tanishaclippy** [comment]
This issue is only for FYs'

**Comment by Tanishaclippy** [comment]
Simran Desai have you registered for the event ?m
