### ISSUE TITLE
Prime numbers

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#13]
Write a program to print all the numbers between 1 -100.

**Comment by isha0904** [comment]
Isha Baviskar FY COMP. I would like to work on this Issue.

**Comment by utkarshaskumbhar** [comment]
I AM UTKARSHA SANTOSH KUMBHAR
FROM SY COMP
PLEASE ASSIGN ME THIS ISSUE

**Comment by Sanskruti21-2002** [comment]
I am Sanskruti Wakode
From SY COMP 
I would like to Work on this Issue

**Comment by Tanishaclippy** [comment]
The issue with good first issue is exclusively for FYs'
