### ISSUE TITLE
Identity matrix

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#14]
Write a program by accepting values from the user to determine whether the matrix is an identity matrix or not .

**Comment by RishitaChourey** [comment]
i would like to work on this
Rishita Chourey
FY comp

**Comment by janhavipunse** [comment]
Janhavi Punse 
SY Computer
I would like to work on this

**Comment by Tanishaclippy** [comment]
This issue is exclusively for FYs .
