### ISSUE TITLE
Odd and even

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#15]
Write a program to find the frequency of odd and even numbers in  a given matrix.
A=[3 4 15]
     [ 2 14 3]
     [ 6 0 1]

**Comment by akanksha1131** [comment]
Akanksha Kale. I would like to work on this. Kindly assign me this issue.

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC
I would like to work on this issue.

**Comment by srushtikage** [comment]
I want to work on this issue pls assign it to me.
Srushti Kage
UCE2022531
FY COMP

**Comment by Tanishaclippy** [comment]
Srushti you can work on this issue till 26th March 11.59 pm.
