### ISSUE TITLE
Count digit alphabets and special character in a string.

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#176]
Write a program in C /javato count the total number of alphabets, digits and special characters in a string.

Test Data :
Input the string : Welcome to w3resource.com

Expected Output :

Number of Alphabets in the string is : 21 
Number of Digits in the string is : 1 
Number of Special characters in the string is : 4

**Comment by RishitaChourey** [comment]
I would like to work on this issue
Rishita Chourey
FY comp

**Comment by Vaishnavi-gaikawad** [comment]
@RishitaChourey ,Yes you can. Upload you solution in the "Solutions" folder by 29 March'23, 11:59pm
