### ISSUE TITLE
Create a blog portal

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#18]
Create a blog portal where users can write any kind of blog, while others can like and share the blog via a unique link.
● Add a rich text editor (with images) to write the blog.
● Public users can search blogs available on the platform.
● Public users can share the blog via a unique link.
● Sort top-performing blogs based on popularity by likes.

**Comment by vaishnavi-3969** [comment]
Vaishnavi Kale
C22020881923
T.Y.Comp.
Interested in working on this

**Comment by shruti-2412** [comment]
@vaishnavi-3969 you can start working on the issue. You have 2 days for it.

**Comment by vaishnavi-3969** [comment]
can I pls submit it by tomorrow I was having exam on Friday I am halfway through the project

**Comment by shruti-2412** [comment]
Sure...

**Comment by vaishnavi-3969** [comment]
> Sure...

Thank you so much

**Comment by shruti-2412** [comment]
@vaishnavi-3969 are you ready with your solution file?

**Comment by vaishnavi-3969** [comment]
> @vaishnavi-3969 are you ready with your solution file?

Yep just few changes remaining will submit it asap

**Comment by shruti-2412** [comment]
Okay
