### ISSUE TITLE
 find the maximum and minimum elements in an array.

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#182]
Write a program in C to find the maximum and minimum elements in an array. 

Test Data :
Input the number of elements to be stored in the array :3
Input 3 elements in the array :
element - 0 : 45
element - 1 : 25
element - 2 : 21
Expected Output :
Maximum element is : 45
Minimum element is : 21

**Comment by isha0904** [comment]
I would like to work on this issue.
ISHA BAVISKAR FY COMP
