### ISSUE TITLE
Battleships in a Board

### ISSUE THREAD

**Issue by RenukaN-123** [Mozilla-Campus-Club-Cummins/Spring-of-Code#183]
Given an **m x n** matrix board where each cell is a battleship **'X'** or empty **'.'**, return the number of the battleships on board.

Battleships can only be placed horizontally or vertically on board. In other words, they can only be made of the shape **1 x k** (1 row, k columns) or **k x 1** (k rows, 1 column), where k can be of any size. At least one horizontal or vertical cell separates between two battleships (i.e., there are no adjacent battleships).

 Example 1:
![battelship-grid](https://user-images.githubusercontent.com/128510933/228206227-80504d1d-c6f0-457f-ad41-6f795996757a.jpg)

Input: board = [["X",".",".","X"],[".",".",".","X"],[".",".",".","X"]]
Output: 2

Example 2:
Input: board = [["."]]
Output: 0
 
Constraints:
m == board.length
n == board[i].length
1 <= m, n <= 200
board[i][j] is either '.' or 'X'.
 
Follow up: Could you do it in one-pass, using only **O(1)** extra memory and without modifying the values board?

**Comment by ruchagosavi** [comment]
Rucha Gosavi
I would like to work on this issue

**Comment by RenukaN-123** [comment]
@ruchagosavi 
You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by RenukaN-123** [comment]
@ruchagosavi 
You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it
