### ISSUE TITLE
 Spiral Matrix

### ISSUE THREAD

**Issue by RenukaN-123** [Mozilla-Campus-Club-Cummins/Spring-of-Code#188]
You start at the cell **(rStart, cStart)** of an **rows x cols** grid facing east. The northwest corner is at the first row and column in the grid, and the southeast corner is at the last row and column.

You will walk in a clockwise spiral shape to visit every position in this grid. Whenever you move outside the grid's boundary, we continue our walk outside the grid (but may return to the grid boundary later.). Eventually, we reach all **rows * cols** spaces of the grid.

Return an array of coordinates representing the positions of the grid in the order you visited them.

### Example 1:
![example_1](https://user-images.githubusercontent.com/128510933/228215644-7f329614-2526-4171-93a7-12e4d4e2275c.png)

Input: rows = 1, cols = 4, rStart = 0, cStart = 0
Output: [[0,0],[0,1],[0,2],[0,3]]

### Example 2:
![example_2](https://user-images.githubusercontent.com/128510933/228215677-f3b5f72f-0d93-4272-9e77-c1d8eff372e4.png)

Input: rows = 5, cols = 6, rStart = 1, cStart = 4
Output: [[1,4],[1,5],[2,5],[2,4],[2,3],[1,3],[0,3],[0,4],[0,5],[3,5],[3,4],[3,3],[3,2],[2,2],[1,2],[0,2],[4,5],[4,4],[4,3],[4,2],[4,1],[3,1],[2,1],[1,1],[0,1],[4,0],[3,0],[2,0],[1,0],[0,0]]
 
_Constraints:_
1 <= rows, cols <= 100
0 <= rStart < rows
0 <= cStart < cols

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake
SY COMP
I would like to work on this issue.

**Comment by ruchagosavi** [comment]
Rucha Gosavi
I would like to wok on this issue

**Comment by RenukaN-123** [comment]
@PiyushaGhodake 
Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 1 April '23 11:59pm

**Comment by RenukaN-123** [comment]
@ruchagosavi 
You have already been assigned one issue. You can work only on one issue at a time .

**Comment by PiyushaGhodake** [comment]
@RenukaN-123 I have submitted the solution. Can u check it.

**Comment by Krush2311** [comment]
closed
