### ISSUE TITLE
Gold for 7 Days of Work.

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#19]
A person is hired for seven days to work on the employer's house and as a compensation a gold bar is paid to him. The gold bar is divided into seven pieces and is connected with each other like a chain. A piece of gold is given to him at the end of everyday work. What and where are the minimum number of cuts to the chain of gold bar pieces will be made, so that you can pay him a piece of gold every day?

**Comment by aarushichopkar** [comment]
I would love to work on this issue
Aarushi Chopkar
TY ENTC

**Comment by Aastha83** [comment]
I am Aastha Thorat from SY Comp.
I would like to work on this issue.

**Comment by Sannidhi26** [comment]
I am sannidhi nandgaonkar
I would like to work on this issue.

**Comment by sanskritisri13** [comment]
Surely willbe assigning you by tonight!
Thank you!

**Comment by bargeshreeya** [comment]
I Shreeya Barge, would like to work on this issue . SY IT

**Comment by vrishitagharte** [comment]
> I would love to work on this issue Aarushi Chopkar TY ENTC

hey aarushi, this issue is assigned to you, the deadline to complete this is of 2 days, i.e., complete it by 29th March, 11:59 pm.
