### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#195]
Given an array "nums" of distinct integers, return all the possible permutations. You can return the answer in any order.

Example 1:

Input: nums = [1,2,3]
Output: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]
Example 2:

Input: nums = [0,1]
Output: [[0,1],[1,0]]
Example 3:

Input: nums = [1]
Output: [[1]]

**Comment by sejalphatangare** [comment]
Sejal Phatangare
Please Assign me this issue

**Comment by prerna-8003** [comment]
@sejalphatangare   You have already been assigned one issue. You can work only on one issue at a time .

**Comment by janhavipunse** [comment]
Janhavi Punse
UCE2021458
I would like to work on this
