### ISSUE TITLE
Multiply Strings

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#196]
Given two non-negative integers "num1" and "num2" represented as strings, return the product of num1 and num2, also represented as a string.

Note: You must not use any built-in BigInteger library or convert the inputs to integer directly.

Example 1:

Input: num1 = "2", num2 = "3"
Output: "6"
Example 2:

Input: num1 = "123", num2 = "456"
Output: "56088"

**Comment by sejalphatangare** [comment]
Sejal Phatangare
Please assign me this issue

**Comment by sejalphatangare** [comment]
Hi @gunjankhatri81 
In the Assignees section I am not able to see my name. If I upload solution then I would be considered as spam , please assign me first. Thank you.
