### ISSUE TITLE
Longest Valid Parentheses

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#197]
Given a string containing just the characters '(' and ')', return the length of the longest valid (well-formed) parentheses
substring
.

Example 1:

Input: s = "(()"
Output: 2
Explanation: The longest valid parentheses substring is "()".
Example 2:

Input: s = ")()())"
Output: 4
Explanation: The longest valid parentheses substring is "()()".
Example 3:

Input: s = ""
Output: 0

**Comment by Rasika-Kanitkar** [comment]
I want to work!
Rasika kanitkar (SY Comp)

**Comment by ruchagosavi** [comment]
Rucha Gosavi
I would like to work on this issue

**Comment by Rasika-Kanitkar** [comment]
@Sru2606  I am done with 3rd PR and it has been merged! Now please assign this issue

**Comment by gunjankhatri81** [comment]
> I want to work! Rasika kanitkar (SY Comp)

Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 1 April '23 11:59pm

**Comment by Rasika-Kanitkar** [comment]
PR request created @gunjankhatri81
