### ISSUE TITLE
Divide Two Integers

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#198]
The integer division should truncate toward zero, which means losing its fractional part. For example, 8.345 would be truncated to 8, and -2.7335 would be truncated to -2.

Return the quotient after dividing dividend by divisor.

Example 1:

Input: dividend = 10, divisor = 3
Output: 3
Explanation: 10/3 = 3.33333.. which is truncated to 3.
Example 2:

Input: dividend = 7, divisor = -3
Output: -2
Explanation: 7/-3 = -2.33333.. which is truncated to -2.

**Comment by ShreyaShetty263** [comment]
would like to work on this 
Shreya Shetty 
sy entc

**Comment by bargeshreeya** [comment]
I Shreeya Barge from SY IT would like to work on this issue, i'm done with my previous one .

**Comment by janhavipunse** [comment]
Janhavi Punse
SY Comp
I would like to work on this
