### ISSUE TITLE
Generate Parentheses

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#199]
Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

Example 1:

Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
Example 2:

Input: n = 1
Output: ["()"]

**Comment by sayli2003** [comment]
Sayli Borole
SY Comp
I would like to work on this issue

**Comment by gunjankhatri81** [comment]
> Sayli Borole SY Comp I would like to work on this issue

Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 1 April '23 11:59pm

**Comment by Krush2311** [comment]
closed
