### ISSUE TITLE
Separate the characters

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#2]
Write a program to separate the characters from the string.

Input:
Welcome

Output:
W e l c o m e

**Comment by ishag8** [comment]
Please assign me to this issue.
Isha Godse

**Comment by Tanishaclippy** [comment]
Yes , you can work on this issue

**Comment by isha0904** [comment]
I would like to work on this issue.
Isha Baviskar (FY COMP)
