### ISSUE TITLE
Spam Detection

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#20]
Create a machine-learning model for spam email detection

**Comment by vaishnavi-3969** [comment]
Vaishnavi Kale
C22020881923
T.Y.Comp.
Interested in working on this

**Comment by Rasika-Kanitkar** [comment]
I would like to work on this issue
Rasika Kanitkar SY Comp
( done with previous issue)

**Comment by shruti-2412** [comment]
@Rasika-Kanitkar are you done with the model ?

**Comment by Rasika-Kanitkar** [comment]
Not yet

**Comment by Rasika-Kanitkar** [comment]
I have time till 12 today n? Full 2 days are assigned n? you had assigned me day before yesterday

**Comment by shruti-2412** [comment]
Yes you can submit till tonight or tomorrow morning also. Just checking with the status.

**Comment by Rasika-Kanitkar** [comment]
Thank you!

**Comment by Rasika-Kanitkar** [comment]
PR raised!Do check
