### ISSUE TITLE
Multiply Strings

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#200]
Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.

Note: You must not use any built-in BigInteger library or convert the inputs to integer directly.

Example 1:

Input: num1 = "2", num2 = "3"
Output: "6"
Example 2:

Input: num1 = "123", num2 = "456"
Output: "56088"

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake.
Sy Comp.
I would like to work on this issue.

**Comment by gunjankhatri81** [comment]
> Piyusha Ghodake. Sy Comp. I would like to work on this issue.

 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by PiyushaGhodake** [comment]
Okk

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT.
I would like to work on this issue
can you please assign this Issue to me?

**Comment by sejalphatangare** [comment]
This Issue is repeated issue.
