### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by Sru2606** [Mozilla-Campus-Club-Cummins/Spring-of-Code#203]
Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

Example 1:

Input: strs = ["flower","flow","flight"]
Output: "fl"
Example 2:

Input: strs = ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.

**Comment by Garima-Kodkani** [comment]
Garima Kodkani
SY EnTC 
I would like to work on this

**Comment by gunjankhatri81** [comment]
> Garima Kodkani SY EnTC I would like to work on this

 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.
