### ISSUE TITLE
Association

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#21]
Given a purchase history for a customer and a large inventory of products, identify those products in which that customer will be interested and likely to purchase. Create a machine leraning model for this.

**Comment by vaishnavi-3969** [comment]
Vaishnavi Kale
C22020881923
T.Y.Comp.
Intersted in working on this

**Comment by shruti-2412** [comment]
@vaishnavi-3969 you can start working on the issue. You have 2 days for it.

**Comment by vaishnavi-3969** [comment]
> @vaishnavi-3969 you can start working on the issue. You have 2 days for it.

I can take any dataset right
?

**Comment by shruti-2412** [comment]
Yes you can

**Comment by vaishnavi-3969** [comment]
Google Colab: https://colab.research.google.com/drive/12U_2F5gi2qWdL_yV2WQNZCXZdI3qGb9c?usp=sharing
