### ISSUE TITLE
Count no of triangles

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#22]
Given a set of points up to n (n>=3) points, no three of which are collinear, count the number of subsets of size 3 that form a triangle containing the origin.

**Comment by akanksha1131** [comment]
Akanksha Kale. Kindly assign me this issue.

**Comment by shruti-2412** [comment]
@akanksha1131 you can start working on the issue. You have 2 days for it.

**Comment by pranotiep06** [comment]
Pranoti Patil
S Y Comp
I would like to work on this issue.

**Comment by shruti-2412** [comment]
@akanksha1131 are you done with the solution ?

**Comment by akanksha1131** [comment]
Yes, ill upload by tonight ?
