### ISSUE TITLE
Next Greater Element(NGE)

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#23]
Given an array, print the Next Greater Element (NGE) for every element. 
(The Next greater Element for an element x is the first greater element on the right side of x in the array. Elements for which no greater element exist, consider the next greater element as -1. )

**Comment by sejalphatangare** [comment]
Please assign me this issue.
Sejal Phatangare
UCE2021457

**Comment by Sanskruti21-2002** [comment]
Sanskruti Wakode
I would like to work on this issue

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake.
I would like to work on this issue.

**Comment by ruchagosavi** [comment]
Rucha Gosavi
I would like to work on this issue!

**Comment by Sannidhi26** [comment]
sannidhi Nandgaonkar
I have completed my first Issue. can you please assign me this issue.
SY comp.

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, could you please assign this issue to me?

**Comment by sanskritisri13** [comment]
assigning this issue to @Sanskruti21-2002 complete it before 11:59pm 29th of March 2023
