### ISSUE TITLE
Prime number between two numbers

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#24]
You are given two integers m and n, and you need to find all the prime numbers between these m and n.

**Comment by SwaroopaDubal** [comment]
Swaroopa Dubal , SY ENTC
I would like to work on this issue, can you plz assign this issue to me??

**Comment by shruti-2412** [comment]
@Anushri07 you can start working on the issue. You have 2 days to do that.

**Comment by shruti-2412** [comment]
You can work on single issue at a time

**Comment by janhavipunse** [comment]
Janhavi Punse
SY comp 
I would like to work on this

**Comment by shruti-2412** [comment]
@janhavipunse you can start working on the issue. You have 2 days for it
