### ISSUE TITLE
 Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by Krush2311** [Mozilla-Campus-Club-Cummins/Spring-of-Code#25]
Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.

 

Example 1:
![histogram1_issue](https://user-images.githubusercontent.com/81237390/226097117-56f02fd7-38ea-4314-87e1-9a4f167afe09.jpg)

Input: heights = [2,1,5,6,2,3]
Output: 10
Explanation: The above is a histogram where width of each bar is 1.
The largest rectangle is shown in the red area, which has an area = 10 units.

Example 2:

![histogram2_issue](https://user-images.githubusercontent.com/81237390/226097124-2f19a904-f3b3-475d-85dc-a73b3b1bade6.jpg)

Input: heights = [2,4]
Output: 4
 

Constraints:

1 <= heights.length <= 105
0 <= heights[i] <= 104

**Comment by NikitaMiraje** [comment]
Nikita Miraje, SY ENTC
Can you plz assign this issue to me???

**Comment by Krush2311** [comment]
@NikitaMiraje l you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it

**Comment by bargeshreeya** [comment]
I Shreeya Barge , SY IT would like to work on this issue

**Comment by pranotiep06** [comment]
Pranoti Patil
S Y Comp
I would like to work on this issue.

**Comment by Krush2311** [comment]
@NikitaMiraje pls go ahead, upload solution in **solutions** folder, deadline 25 March, 11:59pm

**Comment by Krush2311** [comment]
This is how you create a proper PR by mentioning the issue no. in description and not in title of PR. @NikitaMiraje . PLease take care next time
