### ISSUE TITLE
K means clustering documentation

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#26]
Create documentation for the k means clustering algorithm.
It should include all definitions, advantages, disadvantages, real-life example and generalised python code for the algorithm

**Comment by shruti-2412** [comment]
This is a good first issue for FY students to explore machine learning

**Comment by sayli2003** [comment]
Sayli Borole 
SY Comp
I would like to work on this issue
