### ISSUE TITLE
Anagram String Program

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#27]
Write a program to check if two given String is Anagram of each other. 
(An anagram of a string is another string that contains the same characters, only the order of characters can be different. For example, “abcd” and “dabc” are an anagram of each other.)

**Comment by sejalphatangare** [comment]
Please assign me this issue.
Sejal Jayvant Phatangare
UCE2021457

**Comment by sanskritisri13** [comment]
I have assigned this issue to you @sejalphatangare try completing it in 2 days.
