### ISSUE TITLE
Permutations of a String

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#28]
Write a Java program to print all permutations of a given String.
(example:-Below are the permutations of string ABC. 
ABC ACB BAC BCA CBA CAB)

**Comment by sejalphatangare** [comment]
Please assign me this issue
Sejal Jayvant Phatangare
UCE2021457

**Comment by sanskritisri13** [comment]
I have assigned the issue to you @sejalphatangare,try completing it in 2 days from now.

**Comment by sanskritisri13** [comment]
Assigning this issue to @sejalphatangare ,try completing in 2 days from now.

**Comment by sanskritisri13** [comment]
@sejalphatangare do not create a pullrequest now since the deadline's exceeded and the issue's unassigned from your account.

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake.
I would like to work on this issue.

**Comment by PiyushaGhodake** [comment]
@sanskritisri13 I would like to work on this issue.
Piyusha Ghodake.

**Comment by sanskritisri13** [comment]
assigning this task to @PiyushaGhodake ,try completing before 11:59p.m. on 29th of March 2023

**Comment by PiyushaGhodake** [comment]
@sanskritisri13 I had uploaded my solution.

**Comment by vrishitagharte** [comment]
> @sanskritisri13 I had uploaded my solution.

hey piyusha, have you put a proper pull request? thats the only way we can see your code.
