### ISSUE TITLE
Add two complex numbers 

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#29]
you have  to take two complex numbers as structures and add them by creating a user-defined function.
To solving this example, you should have the knowledge of the following C programming topics:

C struct
C Structure and Function

output should be like this with flexlibility of input values :
For 1st complex number
Enter the real and imaginary parts: 2.1
-2.3

For 2nd complex number
Enter the real and imaginary parts: 5.6
23.2
Sum = 7.7 + 20.9i

**Comment by Vaishnavi-gaikawad** [comment]
@isha0904  you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY COMPUTER
I would like to work on this

**Comment by Vaishnavi-gaikawad** [comment]
@janhavipunse , Please note that issue labelled as **_easy_** are only for first years, you can try **_medium_** and _**hard**_ labelled issues

**Comment by isha0904** [comment]
I am done with first, can I work on this issue?

**Comment by Vaishnavi-gaikawad** [comment]
@DurvaTodkari ,Yes you can. Upload you solution in the "Solutions" folder by 26 March'23, 11:59pm

**Comment by Vaishnavi-gaikawad** [comment]
Closed
