### ISSUE TITLE
Largest and smallest word 

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#3]
Write a program to find the largest and the smallest words in the string .

Input :
She likes to play

Output:
Largest word : likes
Smallest word : to

**Comment by SwaroopaDubal** [comment]
Swaroopa Dubal , SY ENTC
I would like to work on this issue, can you plz assign this issue to me??

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC 
I would like to work on this issue.
