### ISSUE TITLE
Happy Number

### ISSUE THREAD

**Issue by Krush2311** [Mozilla-Campus-Club-Cummins/Spring-of-Code#30]
Write an algorithm to determine if a number n is happy.

A happy number is a number defined by the following process:

Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.
Return true if n is a happy number, and false if not.

 

Example 1:

Input: n = 19
Output: true
Explanation:
12 + 92 = 82
82 + 22 = 68
62 + 82 = 100
12 + 02 + 02 = 1
Example 2:

Input: n = 2
Output: false
 

Constraints:

1 <= n <= 231 - 1

**Comment by ishag8** [comment]
Please assign me to this issue.
Isha Godse

**Comment by SwaroopaDubal** [comment]
Swaroopa Dubal , SY ENTC
I would like to work on this issue, can you plz assign this issue to me??

**Comment by Krush2311** [comment]
@ishag8  and @SwaroopaDubal you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it

**Comment by Aastha83** [comment]
I am Aastha Thorat from SY Comp.
I would like to solve this issue.

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
Cummins College of Engineering Pune
SY ENTC
I would like to work on this issue. can you please assign me this issue

**Comment by Krush2311** [comment]
@Prajakta456 go ahead, upload your solution in the solutions folder, deadline is 25th march, 11:59pm
