### ISSUE TITLE
Jump Game

### ISSUE THREAD

**Issue by Krush2311** [Mozilla-Campus-Club-Cummins/Spring-of-Code#31]
A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk such that:

Every adjacent pair of words differs by a single letter.
Every si for 1 <= i <= k is in wordList. Note that beginWord does not need to be in wordList.
sk == endWord
Given two words, beginWord and endWord, and a dictionary wordList, return all the shortest transformation sequences from beginWord to endWord, or an empty list if no such sequence exists. Each sequence should be returned as a list of the words [beginWord, s1, s2, ..., sk].

 

Example 1:

Input: beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]
Output: [["hit","hot","dot","dog","cog"],["hit","hot","lot","log","cog"]]
Explanation: There are 2 shortest transformation sequences:
"hit" -> "hot" -> "dot" -> "dog" -> "cog"
"hit" -> "hot" -> "lot" -> "log" -> "cog"
Example 2:

Input: beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log"]
Output: []
Explanation: The endWord "cog" is not in wordList, therefore there is no valid transformation sequence.
 

Constraints:

1 <= beginWord.length <= 5
endWord.length == beginWord.length
1 <= wordList.length <= 500
wordList[i].length == beginWord.length
beginWord, endWord, and wordList[i] consist of lowercase English letters.
beginWord != endWord
All the words in wordList are unique.
The sum of all shortest transformation sequences does not exceed 105.

**Comment by NikitaMiraje** [comment]
Nikita Miraje, SY ENTC
Can you plz assign this issue to me???

**Comment by Krush2311** [comment]
@NikitaMiraje  you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
Sy ENTC
Cummins college of Engineering, Pune
I would like to work on this issue. Can you please assign this to me?

**Comment by ruchagosavi** [comment]
Rucha Gosavi
I would like to work on this issue

**Comment by Krush2311** [comment]
@ruchagosavi yes, you can go ahead. Submit your solution in **solutions** folder till 26March 11:59pm

**Comment by ruchagosavi** [comment]
@Krush2311 I have created file with solutions yesterday but it I am not getting option of pull request it's problem of server

**Comment by Krush2311** [comment]
@ruchagosavi create a proper pr
Steps:
1. fork the repo
2. switch to your branch
3. add your solution to **solution** folder
4. create pr by mentioning issue no. in description of pr.

**Comment by ruchagosavi** [comment]
@Krush2311  I have pulled my request can u plz assign asap I want to work on other issues?
