### ISSUE TITLE
Linear Regression Model

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#32]
Create a Linear Regression machine learning model.
(Linear regression is one of the easiest and most popular Machine Learning algorithms. It is a statistical method that is used for predictive analysis. Linear regression makes predictions for continuous/real or numeric variables such as sales, salary, age, product price, etc.)

**Comment by Shubhi-73** [comment]
I would like to work on this issue.

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake.
I would like to work on this.

**Comment by sanskritisri13** [comment]
I have assigned the issues to you @Shubhi-73 ,the deadline would be 2 days from now.

**Comment by sanskritisri13** [comment]
@Shubhi-73 you cant work on two issues simultaneously,once one is completely done we can assign you another issue,linear regression model issue wasn't assigned to you to create pull request it won't be accepted,you can wait till it gets assigned to you.

**Comment by PiyushaGhodake** [comment]
I have completed my first issue. Can u assign me this issue?

**Comment by vrishitagharte** [comment]
> Ketki Patil SY COMP Please assign this issue to me.

I'm
 sorry but this issue is only for FYs.
