### ISSUE TITLE
Fibonacci Series using Recursion

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#33]
Write a C Program to generate Fibonacci Series using Recursion.

**Comment by itskrutinewalkar** [comment]
Hi there!
I would like to work on this issue!
Can you please assign it to me?

**Comment by akanksha1131** [comment]
Akanksha Kale. I would like to work on this.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY COMPUTER
I would like to work on this

**Comment by Vaishnavi-gaikawad** [comment]
@janhavipunse and @akanksha1131 Please note that issue labelled as **_easy_** are only for first years, you can try **_medium_** and **_hard_** labelled issues

**Comment by dikshat10** [comment]
Hello I am Diksha Talathi
FY Comp 
Please assign this issue to me

**Comment by Vaishnavi-gaikawad** [comment]
@dikshat10 Yes you can. Upload you solution in the "Solutions" folder by 26 March'23, 11:59pm

**Comment by Vaishnavi-gaikawad** [comment]
Closed
