### ISSUE TITLE
Find duplicates in an Array

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#34]
Given an array a[] of size N which contains elements from 0 to N-1, you need to find all the elements occurring more than once in the given array.

**Comment by RishitaChourey** [comment]
i would like to work on this

**Comment by utkarshaskumbhar** [comment]
I AM UTKARSHA SANTOSH KUMBHAR 
FROM SY COMP 
PLEASE ASSIGN ME THIS ISSUE

**Comment by sanskritisri13** [comment]
Assigning this task to @utkarshaskumbhar,try completing it in 2 days from now.
