### ISSUE TITLE
Delete Middle of Linked List

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#35]
Given a singly linked list, delete middle of the linked list.
( For example, if given linked list is 1->2->3->4->5 then linked list should be modified to 1->2->4->5.)

**Comment by SrushtiPekamwar** [comment]
Want to work on this

**Comment by sanskritisri13** [comment]
Assigning this task to @SrushtiPekamwar,try completing in 2 days.

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC
I would like to work on this issue.

**Comment by ruchagosavi** [comment]
Rucha Gosavi here
I would like to work on this issue
