### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/Spring-of-Code#37]
Implement the partition() and quickSort() functions to sort the array.

(Quick Sort is a Divide and Conquer algorithm. It picks an element as a pivot and partitions the given array around the picked pivot.
Given an array arr[], its starting position is low (the index of the array) and its ending position is high(the index of the array).)

**Comment by Ahana416** [comment]
Ahana Agashe
SY COMP
I would like to work on this.

**Comment by Ketkipatil25** [comment]
Ketki Patil
SY COMP
Please assign this issue to me.

**Comment by sanskritisri13** [comment]
I have assigned the issue to you @Ahana416,try completing it in 2 days from today.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY computer
I would like to work on this

**Comment by sanskritisri13** [comment]
I am assigning this task to @Ketkipatil25,try completing it in 2 days.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY Computer
i would like to work on this

**Comment by Ahana416** [comment]
I am supposed to work on this right? I cannot see if you've assigned it to
me, and it has been assigned to somebody who commented after I did.
It was originally assigned to me but then it got reassigned to somebody
else.
Please look into it. Thank you.

**Comment by Ahana416** [comment]
> I am assigning this task to @Ketkipatil25,try completing it in 2 days.

It was originally assigned to me. Also I commented first.

**Comment by sanskritisri13** [comment]
@Ahana416 you were already assigned some other issue at that point.
@Ketkipatil25 you are already unassigned from this issue,do not create a pull request now,deadline is exceeded.

**Comment by sanskritisri13** [comment]
@Ahana416 i am assigning this issue to you,complete it before 11:59 pm 25/03/2023.

**Comment by sanskritisri13** [comment]
@Ahana416 do not create a pull request now,deadline's exceeded and issue is also unassigned from your account.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY comp
UCE2021458
I would like to work on this

**Comment by ArtiHere** [comment]
I am Arti Tambade.
I would like to work on this issue, could you please assign this issue to me?

**Comment by aarushichopkar** [comment]
I would like to work on this issue.
Aarushi Chopkar
TY ENTC

**Comment by eshadeo** [comment]
@janhavipunse @ArtiHere @bargeshreeya all of you already have issues assigned to you, I am assigning @aarushichopkar, you have 2 days to submit the pull request

**Comment by bargeshreeya** [comment]
my previous one is done
