### ISSUE TITLE
Matrix multiplication in C

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#38]
matrix multiplication in c 

output example:
enter the number of row=3
enter the number of column=3
enter the first matrix element=
1 1 1
2 2 2
3 3 3
enter the second matrix element=
1 1 1
2 2 2
3 3 3
multiply of the matrix=
6 6 6
12 12 12
18 18 18

**Comment by itskrutinewalkar** [comment]
Hi! I am Kruti Newalkar
Can you please assign me this issue?

**Comment by Vaishnavi-gaikawad** [comment]
@itskrutinewalkar  you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it.

**Comment by TanushreeKadus** [comment]
Hello this is Tanushree Kadus from FY comp.
Can you please assign me this issue.

**Comment by Vaishnavi-gaikawad** [comment]
@TanushreeKadus ,Yes you can. Upload you solution in the "Solutions" folder by 26 March'23, 11:59pm

**Comment by isha0904** [comment]
I would like to work on this Issue
Isha Baviskar FY Comp

**Comment by Vaishnavi-gaikawad** [comment]
Yes you can. Upload you solution in the "Solutions" folder by 31 March'23, 11:59pm

**Comment by Vaishnavi-gaikawad** [comment]
Closed
