### ISSUE TITLE
Duplicates 

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#4]
Write a program to remove duplicate elements from the array by accepting the values from the user.

Output:
Enter the no of elements in arr : 6
Enter the elements : 12 13 14 13 56 34
Arr after removing duplicate elements : 12 13 14 56 34

**Comment by Ahana416** [comment]
I would like to work on this.
Ahana Girish Agashe
SY COMP

**Comment by PiyushaGhodake** [comment]
@Tanishaclippy I would like to work on this issue.
Piyusha Ghodake.
