### ISSUE TITLE
Navbar Design 

### ISSUE THREAD

**Issue by ManasiGDeshmukh** [Mozilla-Campus-Club-Cummins/Spring-of-Code#40]
Design a nav bar using HTML, CSS and JavaScript for a website with helps students improve their coding skills.
The site provides theory as well as problems to solve.
Navbar must contain options like
(link to practice.html, theory.html, etc.)
- SignUp/ Login ( link to signup.html)
- practice 
- theory
- courses
- contests 
- leaderboard
- etc.

add extra tabs as you feel suitable.
Note: The nav bar should support multi screen dimensions

**Comment by Prachi-0704** [comment]
Are we supposed to make only the nav bar and not the content of each sub-page?

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC 
I would like to work on this issue.

**Comment by ManasiGDeshmukh** [comment]
@Prachi-0704 
Create Only the nav bar 
(put the links to the subpages)

**Comment by ManasiGDeshmukh** [comment]
@Prachi-0704 
I have assigned you this issue to you
Add your Folder into the Solution Folder and create pull request

Happy Coding!

**Comment by Prachi-0704** [comment]
Where is the solution folder? I can't find it

**Comment by Prachi-0704** [comment]
I have added the files, could you check please?

**Comment by ManasiGDeshmukh** [comment]
@Prachi-0704 
Create a pull request

**Comment by Prachi-0704** [comment]
I made a pull request now. #155

**Comment by ManasiGDeshmukh** [comment]
@Prachi-0704 
There are errors in pull request
Try again
