### ISSUE TITLE
Sign up Page 

### ISSUE THREAD

**Issue by ManasiGDeshmukh** [Mozilla-Campus-Club-Cummins/Spring-of-Code#42]
Design a Sign up Page using HTML, CSS and JavaScript for a website with helps students improve their coding skills.
The site provides theory as well as problems to solve.

name page as signup.html and signup.css

Take Student Details like

- name, phno, address, etc.
- college, university, etc.
- languages, etc.
add more fields as you feel suitable. 

Do not include Nav Bar

Note: The page should support multi screen dimensions

**Comment by kasturimandlik** [comment]
Kasturi Mandlik.
Cummins College of Engineering,Pune
I would like to work on this issue.

**Comment by ManasiGDeshmukh** [comment]
> Kasturi Mandlik. Cummins College of Engineering,Pune I would like to work on this issue.
We will assign you the issue once you have registered to Spring of Code via the google form link sent on mail

**Comment by ManasiGDeshmukh** [comment]
@kasturimandlik 
Add your folder into the solutions folder

**Comment by ManasiGDeshmukh** [comment]
@kasturimandlik 
create a new pull request for this
