### ISSUE TITLE
Log In page

### ISSUE THREAD

**Issue by ManasiGDeshmukh** [Mozilla-Campus-Club-Cummins/Spring-of-Code#43]
Design a Log In Page using HTML, CSS and JavaScript for a website with helps students improve their coding skills.
The site provides theory as well as problems to solve.

name page login.html and login.css

add fields as you feel suitable.
Do not include Nav Bar

Note: The page should support multi screen dimensions

**Comment by kasturimandlik** [comment]
Kasturi Mandlik.
Cummins College of Engineering,Pune
I would like to work on this issue.

**Comment by kasturimandlik** [comment]
@ManasiGDeshmukh  I have completed working on my pervious issue and created a pull request for the same. Can you please assign me this issue now?

**Comment by ManasiGDeshmukh** [comment]
@kasturimandlik 
I have assigned you this issue
Add your folder into Solutions Folder

**Comment by kasturimandlik** [comment]
I have added the solution. Can you once check if it is in the right folder?
