### ISSUE TITLE
Leaderboard page 

### ISSUE THREAD

**Issue by ManasiGDeshmukh** [Mozilla-Campus-Club-Cummins/Spring-of-Code#46]
Design a Leaderboard page using HTML, CSS and JavaScript for a website with helps students improve their coding skills.
The site provides theory as well as problems to solve.

name page leaderB.html and leaderB.css

Leaderboard must contain options like

- student name
- points
- etc
add extra tabs as you feel suitable.

Note: The nav bar should support multi screen dimensions

**Comment by SwaroopaDubal** [comment]
Swaroopa Dubal , SY ENTC
I would like to work on this issue, can you plz assign this issue to me??

**Comment by ManasiGDeshmukh** [comment]
@SwaroopaDubal 
We will assign you the issue once you have registered to Spring of Code via the google form link sent on mail

**Comment by ManasiGDeshmukh** [comment]
@SwaroopaDubal 
I have assigned this issue to you Happy Coding!!

**Comment by ManasiGDeshmukh** [comment]
@SwaroopaDubal 
How is work going on?
Submit pull request by eod

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, could you please assign this issue to me?
