### ISSUE TITLE
C program to sort names in alphabetical order

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#47]
User has to enter number of names, and those names are required to be sorted in alphabetical order with the help of strcpy() function.

for example (output):
Enter number of names:
5
Enter names in any order:
Pinky
Lucky
Ram
Appu
Bob
The sorted order of names is:
Appu
Bob
Lucky
Pinky
Ram

**Comment by Vaishnavi-gaikawad** [comment]
@RishitaChourey  you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it.

**Comment by Aastha83** [comment]
I am Aastha Thorat from SY Comp.
I would like to solve this issue.

**Comment by Vaishnavi-gaikawad** [comment]
@Aastha83 all the issues labeled easy are only for FY's. You can try the medium and hard level issues

**Comment by Vaishnavi-gaikawad** [comment]
@isha0904 ,Yes you can. Upload you solution in the "Solutions" folder by 26 March'23, 11:59pm

**Comment by Vaishnavi-gaikawad** [comment]
Closed
