### ISSUE TITLE
Program to print star pattern.

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#49]
write a program to print heart star pattern using loops.

**Comment by isha0904** [comment]
Can you guide me how to upload the solution?

**Comment by Vaishnavi-gaikawad** [comment]
once you fork the  repository, add your solution to **_solutions_** folder of your _forked_ repository, and then create your pull request. If you have any doubt refer the "first contribution" doc shared via mail

**Comment by isha0904** [comment]
Done.
