### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#5]
Write a program to print the following pattern:
 &&&&
 &&&
 &&
 &

**Comment by Sanskruti21-2002** [comment]
Sanskruti Wakode
SY COMP
I Would like to work on this issue

**Comment by ambi-04** [comment]
I would like to work on this
Ambika Deshmukh FY IT

**Comment by Tanishaclippy** [comment]
Ambika deshmukh you are already assigned issue #16 .You can work at one issue at a time

**Comment by utkarshaskumbhar** [comment]
I am utkarsha kumbhar
please assign me this issue
