### ISSUE TITLE
find a word which has the highest number of repeated letters. 

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#52]
Write a program to find a word in a given string which has the highest number of repeated letters.
EXAMPLE -:
INPUT-she sold her olive shirt to mr federer.
 OUTPUT-federer.

**Comment by ananahyeah** [comment]
This issue labeled 'Easy' is only for FYs.

**Comment by RishitaChourey** [comment]
I would like to work on this issue
FY comp
Rishita Chourey

**Comment by isha0904** [comment]
Hi there I would like to work on this issue.
Isha Baviskar FY Comp
