### ISSUE TITLE
C Program to check the given number is an Armstrong or not

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#53]
Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are the Armstrong numbers.

Eg 
input: 127
Ouput format: No it's not an armstrong no.

**Comment by itskrutinewalkar** [comment]
Hey there! I would like to work on this issue, can you please assign me this issue?

**Comment by itskrutinewalkar** [comment]
I am CCEW student from FY IT.

> Hey there! I would like to work on this issue, can you please assign me this issue?

**Comment by Vaishnavi-gaikawad** [comment]
@itskrutinewalkar  you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it.

**Comment by itskrutinewalkar** [comment]
Hi there!!
I've made a PR to my first issue #60.
Can you please assign me this issue?

**Comment by Vaishnavi-gaikawad** [comment]
Yes you can. Upload you solution in the "Solutions" folder by 24 March'23, 11:59pm

**Comment by Vaishnavi-gaikawad** [comment]
@itskrutinewalkar ,you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it.

**Comment by itskrutinewalkar** [comment]
Hi there!
I've made a pull request to issue #56 
I would like to work on this issue
Can you please assign it to me

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC 
I would like to work on this issue.

**Comment by ambi-04** [comment]
Ambika Deshmukh
First Year IT
Can I work on this?

**Comment by Vaishnavi-gaikawad** [comment]
@Prachi-0704 ,all the issues labeled **easy** are only for FY's. You can try the **_medium_** and **_hard_** level issues

**Comment by ambi-04** [comment]
Can I work on this?
Ambika Deshmukh
FY IT

**Comment by itskrutinewalkar** [comment]
> Hi there! I've made a pull request to issue #56 I would like to work on this issue Can you please assign it to me

Hi there can you please assign this issue to me?

**Comment by Vaishnavi-gaikawad** [comment]
@itskrutinewalkar  ,You can't work on 2 issue at a time let first your PR of issue no #56 get merged so that ,I can assinge you this issue if no one comments .

**Comment by Vaishnavi-gaikawad** [comment]
@itskrutinewalkar  ,Yes you can. Upload you solution in the "Solutions" folder by 26March'23, 11:59pm

**Comment by Vaishnavi-gaikawad** [comment]
CLOSED
