### ISSUE TITLE
Increasing order 

### ISSUE THREAD

**Issue by Tanishaclippy** [Mozilla-Campus-Club-Cummins/Spring-of-Code#54]
Write a program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples.

Example :
List : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
Output :  [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]

**Comment by Aastha83** [comment]
I am Aastha Thorat from SY Comp.
I would like to solve this issue.

**Comment by Tanishaclippy** [comment]
This issue is only for FYs

**Comment by Tanishaclippy** [comment]
Issues with label good first issue are exclusively for FYs'
