### ISSUE TITLE
To give grade to a student

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#56]
marks<30 is C grade
30<= marks <70 is B grade
70<= marks <90 is A grade
90<= marks <=100 is A+

**Comment by kasturimandlik** [comment]
Kasturi Mandlik.
I would like to work on this issue.

**Comment by janhavipunse** [comment]
Janhavi Punse 
I would like to work on this

**Comment by itskrutinewalkar** [comment]
Hi there!
I am Kruti Newalkar from FY IT.
I want to work on this issue!
Can you please assign it to me?

**Comment by Chaitralikore** [comment]
@itskrutinewalkar ,Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 24March'23 11:59pm

**Comment by TanushreeKadus** [comment]
Hello I am Tanushree Kadus from FY comp .
I would like to work on this issue

**Comment by itskrutinewalkar** [comment]
Hi there!
I just wanted to confirm that when this issue was assigned to me i.e on 22nd,  I made a PR on that day itself.
Have you received the PR?

**Comment by Chaitralikore** [comment]
CLOSED
