### ISSUE TITLE
Find the no of numbers less than a given number (but only those having odd no of digits.)

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#58]
IF a user inputs a number eg. 1200
then take into consideration only such numbers<1200 that have odd no of digits i.e 5,3,1
for 1200,
count those between 100-999
and 1-9
note : there is no limit in the number of digits a user can input.
 the program should also be able to give the count for large numbers.like 1999900

**Comment by Sannidhi26** [comment]
I would like to work on this issue
Sannidhi Nandgaonkar
Sy comp

**Comment by Shrey63** [comment]
I would like to work on this issue

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC
I would like to work on this issue.

**Comment by RishitaChourey** [comment]
Can you please assign me this issue
i have sent the pull request for my previous issue
Rishita Chourey FY comp

**Comment by gunjankhatri81** [comment]
> I would like to work on this issue Sannidhi Nandgaonkar Sy comp

You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by gunjankhatri81** [comment]
> Prachi Patil SY ENTC I would like to work on this issue.

You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.
