### ISSUE TITLE
Super Washing Machines

### ISSUE THREAD

**Issue by Krush2311** [Mozilla-Campus-Club-Cummins/Spring-of-Code#59]
You have n super washing machines on a line. Initially, each washing machine has some dresses or is empty.

For each move, you could choose any m (1 <= m <= n) washing machines, and pass one dress of each washing machine to one of its adjacent washing machines at the same time.

Given an integer array machines representing the number of dresses in each washing machine from left to right on the line, return the minimum number of moves to make all the washing machines have the same number of dresses. If it is not possible to do it, return -1.

 

Example 1:

Input: machines = [1,0,5]
Output: 3
Explanation:
1st move:    1     0 <-- 5    =>    1     1     4
2nd move:    1 <-- 1 <-- 4    =>    2     1     3
3rd move:    2     1 <-- 3    =>    2     2     2

Example 2:

Input: machines = [0,3,0]
Output: 2
Explanation:
1st move:    0 <-- 3     0    =>    1     2     0
2nd move:    1     2 --> 0    =>    1     1     1

Example 3:

Input: machines = [0,2,0]
Output: -1
Explanation:
It's impossible to make all three washing machines have the same number of dresses.
 

Constraints:

1. n == machines.length
2. 1 <= n <= 10^4
3. 0 <= machines[i] <= 10^5

**Comment by Krush2311** [comment]
@SwaroopaDubal you have already been assigned an issue. You can work only on 1 issue at a time. Once you complete it you may work on this issue if no one else comments on it.

**Comment by ruchagosavi** [comment]
I am Rucha Gosavi  from SY Comp I would like to work on this issue can u plz assign me?

**Comment by bargeshreeya** [comment]
I Shreeya Barge , SY IT would like to work on this issue

**Comment by pranotiep06** [comment]
Pranoti Patil
S Y Comp
I would like to work on this issue.

**Comment by Krush2311** [comment]
@bargeshreeya go ahead, pls add your solution to **"solutions"** folder, deadline is 25th March 11:59pm

**Comment by ruchagosavi** [comment]
I am Rucha Gosavi 
I would like to work on this issue

**Comment by Krush2311** [comment]
@bargeshreeya please create proper pr
