### ISSUE TITLE
Identify Palindromes 

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#6]
Ask user to enter a string, tell whether it is a palindrome Or not a palindrome

Note:Pallindrome is a word/number that remains the same when read from both ends
Eg :madam

Input:     madam
Output:  it is a palindrome.

**Comment by kasturimandlik** [comment]
Kasturi Mandlik.
I would like to work on this issue.

**Comment by ArtiHere** [comment]
I am Arti Tambade.
I would like to work on this issue, Could you assign this issue to me?

**Comment by srushtikage** [comment]
I want to work on this issue.
Srushti Kage
UCE2022531
FY Comp
