### ISSUE TITLE
Find even numbers in an array and store them in another one, find sum of digits of each of these numbers and form a new array, reverse this new array.

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#60]
Find even numbers in an array and store them in another one, find sum of digits of each of these numbers and form a new array, reverse this new array and give output
example:
INPUT={12 , 19 , 26 , 42 , 13 , 11 , 99}
OUTPUT={  6 , 8 , 3  }

**Comment by Solivagant01** [comment]
I am Aastha Narawade from FY Computer Science
I would like to work on this issue
