### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by Krush2311** [Mozilla-Campus-Club-Cummins/Spring-of-Code#61]
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

 
Example 1:
![rainwatertrap_issue](https://user-images.githubusercontent.com/81237390/226101581-57825b8b-1a12-4254-9d43-cebd69ae259c.png)

Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6
Explanation: The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped.

Example 2:

Input: height = [4,2,0,3,2,5]
Output: 9
 

Constraints:

n == height.length
1 <= n <= 2 * 10^4
0 <= height[i] <= 10^5

**Comment by sejalphatangare** [comment]
Please assign this issue to me.
Sejal Jayvant Phatangare
UCE2021457

**Comment by Anjali2312-Thombare** [comment]
Hello,
Anjali Thombare here,
I would like to solve this issue
