### ISSUE TITLE
 Display any given number as its roman equivalent. 

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/Spring-of-Code#62]
Write a general purpose function to display any given number as its roman equivalent. (Eg. 10 = X)

**Comment by ishag8** [comment]
Please assign me this issue.
Isha Godse

**Comment by Sannidhi26** [comment]
I would like to work on this issue
Sannidhi Nandgaonkar
Sy comp

**Comment by RishitaChourey** [comment]
I would like to work on this issue
Rishita Chourey 
Fy comp

**Comment by Vaishnavi-gaikawad** [comment]
@RishitaChourey ,yes you can work on this issue.
