### ISSUE TITLE
Multiplication Table of any Number

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#63]
Write a program in C to print the Multiplication Table of any Number. Take input from the user.

**Comment by kasturimandlik** [comment]
Kasturi Mandlik.
I would like to work on this issue.

**Comment by itskrutinewalkar** [comment]
Hi there! I am Kruti Newalkar from FY IT.
I would like to work on this issue
Can you please assign it to me?

**Comment by Aastha83** [comment]
I am Aastha Thorat from SY Comp. 
I would like to solve this issue.

**Comment by Solivagant01** [comment]
I am Aastha Narawade from FY Computer Science
I would like to work on this issue

**Comment by itskrutinewalkar** [comment]
Hi there!
I would like to work on this issue!
Can you please assign it to me?

**Comment by isha0904** [comment]
Hi there I would like to work on this issue.
Isha Baviskar FY Comp

**Comment by Chaitralikore** [comment]
@Aastha83 this is an easy issue and it can't be assigned to SY student.

**Comment by Chaitralikore** [comment]
@Solivagant01 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it

**Comment by isha0904** [comment]
Hi there I would like to work on this issue.
Isha Baviskar FY Comp

**Comment by Chaitralikore** [comment]
@itskrutinewalkar You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by isha0904** [comment]
Hi there I would like to work on this issue.
Isha Baviskar
 FY Comp

**Comment by itskrutinewalkar** [comment]
Hi there!
Can you please assign me this issue?

**Comment by isha0904** [comment]
Hi there I would like to work on this issue.
Isha Baviskar
FY Comp

**Comment by mokshadashirode** [comment]
Fy ENTC
Can you please assign me this issue
