### ISSUE TITLE
Find Roots of Quadratic Equation

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#64]
Write a program in C to find Roots of Quadratic Equation.

**Comment by NikitaMiraje** [comment]
Nikita Miraje , SY ENTC
I would like to work on this issue, can you plz assign this issue to me??

**Comment by Anushri07** [comment]
I would like to work on this issue 
Anushri Chitte SY ENTC

**Comment by Chaitralikore** [comment]
Yes! @NikitaMiraje you can work on it. The deadline would be 22-03-23.

**Comment by Chaitralikore** [comment]
@Anushri07 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
I would like to work on this 
Janhavi Punse 
SY btech comp

**Comment by Chaitralikore** [comment]
@janhavipunse You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
i have now completed my first issue can i work on this now?

**Comment by Chaitralikore** [comment]
@janhavipunse You have already been assigned 3rd issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it

**Comment by Chaitralikore** [comment]
@Sannidhi26 this is a very easy level issue and can't be assigned to SY student

**Comment by Sannidhi26** [comment]
@Chaitralikore but this is medium labelled issue

**Comment by bargeshreeya** [comment]
I, shreeya barge would like to work on this issue , my previous one is done

**Comment by Chaitralikore** [comment]
@Sannidhi26 it is medium level but for FY. Comparing to SY level, finding roots of quadratic equation is an very easy issue!

**Comment by mokshadashirode** [comment]
FY ENTC
I would like to work on this issue
