### ISSUE TITLE
Move all negative numbers to beginning and positive to end with constant extra space

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#65]
An array contains both positive and negative numbers in random order. Rearrange the array elements so that all negative numbers appear before all positive numbers.

Examples : 

Input: -19, 11, -13, -5, 6, -7, 5, -3, -6
Output: -19 -13 -5 -7 -3 -6 11  6  5

**Comment by RishitaChourey** [comment]
i would like to work on this

**Comment by Sannidhi26** [comment]
I would like to work on this problem statement 
Sannidhi Nandgaonkar
Sy comp

**Comment by RishitaChourey** [comment]
I have completed 2 PR 
Please assign me this issue 
Rishita Chourey FY comp

**Comment by ananahyeah** [comment]
YOU may work on this #65 issue
deadline: 24 March, 11.59pm

**Comment by ananahyeah** [comment]
@RishitaChourey

**Comment by ananahyeah** [comment]
I have assigned it.
YOU may work on this #65
<https://github.com/Mozilla-Campus-Club-Cummins/Spring-of-Code/issues/65>
 issue
deadline: 24 March, 11.59pm

**Comment by ananahyeah** [comment]
@ sannidhi, this issue is only for FYs

**Comment by ananahyeah** [comment]
CLOSED
