### ISSUE TITLE
Find n'th Smallest and Largest Element in an Unsorted Array

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#66]
Find the n’th  Smallest/Largest Element in an Unsorted Array. Given that all array elements are distinct.
Input: array[ ] = {7, 10, 4, 3, 20, 15}, n = 4 
Output: 4th-smallest= 10 
             4th -largest  = 7

**Comment by Anjali2312-Thombare** [comment]
Anjali Thombare 
I would like to work on this issue

**Comment by srushtikage** [comment]
I want to work on this issue.
Srushti Kage
UCE2022531
FY Comp

**Comment by prerna-8003** [comment]
@Anjali2312-Thombare 
@srushtikage   You have already been assigned one issue. You can work only on one issue at a time .
