### ISSUE TITLE
C program to design a digital clock 

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#67]
• Generate a digital clock using C program. The logic behind to implement this program -

- Initialize hour, minute, seconds with 0.
- Run an infinite loop.
- Increase second and check if it is equal to 60 then increase minute and reset second to 0.
- Increase minute and check if it is equal to 60 then increase hour and reset minute to 0.
- Increase hour and check if it is equal to 24 then reset hour to 0.

**Comment by Chaitralikore** [comment]
@Anushri07 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY comp 
UCE2021458
I would like to work on this

**Comment by Chaitralikore** [comment]
@janhavipunse You have already been assigned 3rd issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it
