### ISSUE TITLE
pairs from integer array whose sum is equal to given number

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#68]
You have given an integer array and a number, you need to write a program to find all elements in the array whose sum is equal to the given number. Remember, the array may contain both positive and negative numbers, so your solution should consider that too
 accept input from user and also the target sum from user
output= the pairs which give sum equal to the target sum

**Comment by NikitaMiraje** [comment]
I would like to work on this issue...can you plz assign this issue to me???

**Comment by Sannidhi26** [comment]
I would like to work on this issue
Sannidhi Nandgaonkar
Sy comp

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, Could you assign this issue to me?

**Comment by itskrutinewalkar** [comment]
Hi there!
I would Like to work on this issue
Can you please assign it to me?

**Comment by itskrutinewalkar** [comment]
Hi there!
I would like to work on this issue!
Can you please assign it to me?

**Comment by itskrutinewalkar** [comment]
I am from FY

> Hi there! I would like to work on this issue! Can you please assign it to me?

**Comment by itskrutinewalkar** [comment]
Hi there! Can you please assign me this issue?

**Comment by itskrutinewalkar** [comment]
Hi there! I am not aware which issue I have been assigned which is yet to be submitted because all the issues which were assigned to me were completed and merged as well. Can you please let me know the issue no?
