### ISSUE TITLE
remove a given number from integer array

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#69]
Remove a given number from an integer array and print new array without that number.
example: An array without the number 9
input:
arr[7]={1,39,9,4,9,16,76}
output=
array[]={ 1,39,4,16,76}

**Comment by Aastha83** [comment]
I am Aastha Thorat from SY Comp.
I would like to work on this issue.

**Comment by AbhaBarge** [comment]
Abha Barge FY Comp. Please assign this issue to me.

**Comment by Shrey63** [comment]
I am Shreya Agrawal i would like to work on this issue

**Comment by ananahyeah** [comment]
Abha Barge, start working on this issue
you deadline is 24 march 11.59 pm

**Comment by ananahyeah** [comment]
@ aastha , rucha this issue is only for FYs
