### ISSUE TITLE
Tell number of vowels in a string

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#7]
Write a program to tell no of vowels in a string given by user. 
Input : grapefruit
Output : vowels = 4

**Comment by ishag8** [comment]
Please assign me this issue

**Comment by Sanskruti21-2002** [comment]
Sanskruti Wakode
SY COMP
I would like to work on this issue

**Comment by ananahyeah** [comment]
this issue is ONLY for FYs

**Comment by srushtikage** [comment]
I want to work on this issue pls assign it to me.
Srushti Kage
UCE2022531
FY Comp
