### ISSUE TITLE
C program to create a Simple Calculator 

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#70]
Prerequisite knowledge :
•  switch statement 
•  break and continue statements

**Comment by alwaystanaya20** [comment]
Vaibhavi Thakare
SY Comp
I'd love to work on this issue!

**Comment by Chaitralikore** [comment]
Yes you can work on this issue. The deadline will be 22-03-2023

**Comment by Sanskruti21-2002** [comment]
I am Sanskruti Wakode
SY COMP 
I would like to work on this issue

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, could you please assign this issue to me?

**Comment by isha0904** [comment]
I would like to work on this issue.
Isha Baviskar (FY COMP)

**Comment by Chaitralikore** [comment]
@Solivagant01 Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 28March'23 11:59pm

**Comment by Chaitralikore** [comment]
@Solivagant01 your deadline is over!
