### ISSUE TITLE
Decision Tree documentation

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#71]
Create documentation for the decision tree algorithm
It should include all definitions, advantages, disadvantages, real-life examples and generalized python code for the algorithm

**Comment by shruti-2412** [comment]
This is a good first issue for FY students to explore machine learning

**Comment by PiyushaGhodake** [comment]
Piyusha Ghodake.(SY COMP)
I would like to work on this issue.

**Comment by shruti-2412** [comment]
@PiyushaGhodake you can strat working on the issue. You have 2 days for it. Try to include images and gifs explaining the concept in your readme file.

**Comment by PiyushaGhodake** [comment]
@shruti-2412 Can u pls check the documentation?
