### ISSUE TITLE
To read first line from a file.

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#72]
Write a C program to read first line from a file.
Prerequisite knowledge:
• file handling 
• programming strings

**Comment by Anushri07** [comment]
can assign this issue to me?
Anushri Chitte sy entc cummins

**Comment by Chaitralikore** [comment]
Yes! @Anushri07 you can work on it. The deadline would be 22-03-23.

**Comment by Aastha83** [comment]
I am Aastha Thorat, from SY Comp.
I have completed my first issue, would you please assign this issue to me.

**Comment by Chaitralikore** [comment]
@Aastha83 can't assign this issue as it is an easy issue for a SY student.
