### ISSUE TITLE
Array Data Structure Documentation

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#73]
Explain the Array Data structure
how it works
how to create
try to add code snippets, pictures & gif's explaining the concept
Time complexity, the Space complexity of each operation performed on the Array
Explain functions used in Array

Note: Create a readme.md file

**Comment by sakshi-jadhav** [comment]
I am Sakshi Jadhav
TY IT (CCEW)
I would like to work in this issue

**Comment by Sannidhi26** [comment]
I would like to work on this issue
Sannidhi Nandgaonkar
Sy comp

**Comment by shruti-2412** [comment]
While creating pull request add the file in the solutions folder
