### ISSUE TITLE
Tree Data structure Documentation

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#74]
Explain the Tree Data structure
how it works
how to create
try to add code snippets, pictures & gif's explaining the concept
Time complexity, the Space complexity of each operation performed

Note: Create a readme.md file

**Comment by Aastha83** [comment]
I am Aastha Thorat form SY Comp.
I would like to work on this issue.

**Comment by shruti-2412** [comment]
@Aastha83 you can start working on the issue. You have 2 days to complete it. Try to include images and gifs explaining the topic in the readme file

**Comment by shruti-2412** [comment]
While creating pull request add the file in the solutions folder
