### ISSUE TITLE
Python Program to create a Countdown Timer

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#75]
Prerequisite knowledge:
• Python while loop
• Python time module 
• Python divmod()

**Comment by Rithik14** [comment]
Hey can i work on your issue..

**Comment by Chaitralikore** [comment]
It is only for Cummins College of Engineering students!

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
Cummins College of Engineering.
I would like to work on this issue.

**Comment by SwaroopaDubal** [comment]
Swaroopa Dubal , SY ENTC ,Cummins
I would like to work on this issue, can you plz assign this issue to me??

**Comment by Chaitralikore** [comment]
You can be assigned one issue at a time. After completion another will be
assigned.

--
Mozilla Campus Club
Cummins College of Engineering
Pune

**Comment by Chaitralikore** [comment]
@kasturimandlik You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by Chaitralikore** [comment]
@SwaroopaDubal You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by Chaitralikore** [comment]
@aditisinghal1210 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by kasturimandlik** [comment]
@Chaitralikore I have completed working on my pervious issue and created a pull request for the same. Can you please assign me this issue now?

**Comment by pranotiep06** [comment]
Pranoti Patil
S Y Comp
I would like to work on this issue.

**Comment by syd-faiz** [comment]
I noticed there is an open issue regarding #75. I would like to contribute to this project and I am interested in working on this issue. Could you please assign this issue to me? I am excited to collaborate with you and contribute to the development of this project.

Thank you for your time and consideration.

**Comment by aditisinghal1210** [comment]
> @aditisinghal1210 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

Hey i have finished my previous issue..can u pls assign me

**Comment by Rasika-Kanitkar** [comment]
I would like to work on this issue
Rasika Kanitkar SY Comp

**Comment by Chaitralikore** [comment]
@Rasika-Kanitkar You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by Rasika-Kanitkar** [comment]
Rasika Kanitkar
SY Comp
Done with previous issue @Chaitralikore assign me with this

**Comment by Chaitralikore** [comment]
@sejalphatangare You have already been assigned 2nd issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it
