### ISSUE TITLE
Graph Data Structure Documentation

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/Spring-of-Code#76]
Explain the Graph Data structure
how it works
how to create
try to add code snippets, pictures & gif's explaining the concept
Time complexity, the Space complexity of each operation 

Note: Create a readme.md file

**Comment by Anjali2312-Thombare** [comment]
Anjali Thombare 
I would like to work on this issue

**Comment by Anjali2312-Thombare** [comment]
I am not able to solve this issue due some problems.
I just want to inform you that you can assign it to someone else

**Comment by Sanskruti21-2002** [comment]
Sanskruti Wakode
I would like to work on this issue

**Comment by shruti-2412** [comment]
@Sanskruti21-2002 you have not registered for the event. First register then I can assign you the issue.

**Comment by shruti-2412** [comment]
@Sanskruti21-2002 you can start working on the issue now. You have 2 days for it. Also while adding PR add the file in the solutions folder.
