### ISSUE TITLE
Calculate the Execution Time of Methods

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#78]
Write a program to calculate the execution time of normal methods and recursive methods in Java.
Prerequisite knowledge:
• Java methods 
• Java recursion

**Comment by SwaroopaDubal** [comment]
Swaroopa Dubal , SY ENTC
I would like to work on this issue, can you plz assign this issue to me??

**Comment by Chaitralikore** [comment]
@aditisinghal1210 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by Chaitralikore** [comment]
@SwaroopaDubal You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY computer
I would like to work on this

**Comment by Chaitralikore** [comment]
@janhavipunse You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
> @janhavipunse You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

I've completed my first issue can I work on this?

**Comment by aditisinghal1210** [comment]
> @aditisinghal1210 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

I have finished my first issue,pls assign it to me as I requested first.

Aditi Singhal

**Comment by Chaitralikore** [comment]
@aditisinghal1210 as this one is easy for ty student it can't be assigned to you.

**Comment by Chaitralikore** [comment]
@pranotiep06 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by janhavipunse** [comment]
Janhavi Punse
SY Comp
UCE2021458
I have finished my issue, I can work on this now?

**Comment by Chaitralikore** [comment]
@janhavipunse Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 28March'23 11:59pm

**Comment by janhavipunse** [comment]
> @janhavipunse Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 28March'23 11:59pm

Done , I have submitted it in solutions folder
