### ISSUE TITLE
Create your own Game!!

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#79]
Create a Simple Game, using nothing but HTML and JavaScript.

**Comment by alwaystanaya20** [comment]
Vaibhavi Thakare
SY Comp

I'd love to work on the given problem statement

**Comment by Chaitralikore** [comment]
@alwaystanaya20 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by Chaitralikore** [comment]
@aditisinghal1210 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
Cummins college of Engineering, Pune
I would like to work on this issue. Can you please assign me this issue?

**Comment by Chaitralikore** [comment]
@Rasika-Kanitkar You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by Chaitralikore** [comment]
@Shrey63 Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 26March'23 11:59pm
