### ISSUE TITLE
Convert string to lower case alphabets

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#8]
Write a program asking user to enter a string in capital case letters, Conert the string to lower case. 
Input: BATMAN IS HEROIC. 
output:Batman is heroic

**Comment by aditisinghal1210** [comment]
Aditi Singhal TY ENTC ,I would like to work on this.

**Comment by ChetnaNBattawar** [comment]
Chetna Battawar FY IT , I would like to work on this issue.

**Comment by ananahyeah** [comment]
Chetna ,Your deadline is 24 march, 11.59pm
While creating pull request add the file in the solutions folder
