### ISSUE TITLE
Create a password 

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#80]
Create a web page that asks the user to enter a password.  Your JavaScript program should include:

- A function
- Variables
- An if statement
- An alert
- A text box
- A hyperlink

**Comment by isha-73** [comment]
Isha Bule - I want to work on it

**Comment by Rasika-Kanitkar** [comment]
Rasika Kanitkar
SY Comp (UCE2021630)

**Comment by Chaitralikore** [comment]
@isha-73 You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

**Comment by GouriDhampalwar** [comment]
Gouri Dhampalwar-I want to work on this

**Comment by saakshii12** [comment]
I want to work on this
Sakshi Umredkar
FY INSTRU
UIN2022764

**Comment by Chaitralikore** [comment]
@GouriDhampalwar Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 24March'23 11:59pm

**Comment by Shrey63** [comment]
I would like to work on this issue

**Comment by Rasika-Kanitkar** [comment]
> @Rasika-Kanitkar You have already been assigned one issue. You can work only on one issue at a time . Once you complete it you may work on this issue if no one else comments on it.

I want to work on this!I am done with my previous issue

**Comment by Rasika-Kanitkar** [comment]
@Chaitralikore Are you there? Do reply fast

**Comment by Chaitralikore** [comment]
@Rasika-Kanitkar Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 28March'23 11:59pm

**Comment by Rasika-Kanitkar** [comment]
ok!
