### ISSUE TITLE
Python program to print Emojis

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/Spring-of-Code#81]
Create emojis with the help of  Unicodes, CLDR names and emoji module.

**Comment by aditisinghal1210** [comment]
Aditi Singhal. I would like to work on this issue.

**Comment by sanikachavan18** [comment]
Sanika Chavan
SY COMP
UCE2021510 
Please assign me this issue

**Comment by AbhaBarge** [comment]
Abha Barge FY Comp. Please assign this issue to me.

**Comment by Chaitralikore** [comment]
@sanikachavan18 Yes you can work on this issue. Pls upload your solution in the folder named "Solutions". Your deadline 24March'23 11:59pm.

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC
I would like to work on this issue.

**Comment by Chaitralikore** [comment]
@Prachi-0704 this type of easy issue is for Fy's only.
