### ISSUE TITLE
Virtual Dice site

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#83]
This site is virtual dice for two players.On every refresh it gives a dice roll for both people and tell who has bigger no on dice.
You have to use random function to get this functionality to get random nos on both dices between 1 to 6;And shows image having same no on site for both players.Also you should display who is winner or its draw.
(use necessary images and write function for the issue)

**Comment by Shubhi-73** [comment]
I would like to work on this issue.

**Comment by Rasika-Kanitkar** [comment]
I would love to work on this
Rasika kanitkar
SY Comp(UCE2021630)
