### ISSUE TITLE
Skill table for portfolio

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#84]
Our client needs his personal site showcasing his skills and his rating for them .So we need to create a table naming skills and then rating infront of it.

**Comment by sayli2003** [comment]
Hi,
I would like to work on this issue

Sayli Borole
Sy
Comp

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
SY ENTC
Cummins College of Engineering,Pune
I would like to work on this issue. Can you please assign this to me?

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC
CCOEW
I would like to work on this issue.

**Comment by aditisinghal1210** [comment]
I would like to work on this.

Aditi Singhal

**Comment by aditisinghal1210** [comment]
Hey ,made a pull request,pl check.

**Comment by RutujaKande** [comment]
@aditisinghal1210  your deadline is over,so you can work on other issue!

**Comment by aditisinghal1210** [comment]
> @aditisinghal1210  your deadline is over,so you can work on other issue!

Hi! I had made a pull request within the deadline,but u checked it today..if u had suggested changes earlier,I would have made them in the deadline...

**Comment by aditisinghal1210** [comment]
Hey made the pull request pl check

**Comment by RutujaKande** [comment]
@aditisinghal1210 your pull request is merged
