### ISSUE TITLE
Card game

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#86]
We have a deck of card every card has a suit and a rank suit is from spade Diamond heart and club and rank is ace, two, Three, four ,five, six ,seven ,eight ,Jack, queen and king write a function which displays N random  cards from the Deck and also removes them from the Deck .Also write function shuffle to shuffle all the cards.

**Comment by aditisinghal1210** [comment]
Aditi Singhal. I would like to work on this

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, Could you assign this issue to me?

**Comment by RutujaKande** [comment]
Arti you are already assigned with other issue, you can work on this after previous one

**Comment by sejalphatangare** [comment]
Sejal Phatangare 
Please assign me this issue.

**Comment by ShreyaShetty263** [comment]
Shreya Shetty 
would like to work on this issue

**Comment by sayli2003** [comment]
Sayli Borole
SY COMP
I would like to work on this issue

**Comment by RutujaKande** [comment]
@ShreyaShetty263 you are assigned with this issue

**Comment by Orange-5** [comment]
@ShreyaShetty263 your deadline is over

**Comment by ArtiHere** [comment]
@RutujaKande , I am free now can you please assign this issue to me?
