### ISSUE TITLE
Library management System

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#87]
Our main objective in this project is to create a library management system wherein students can issue books and the admin or librarian can update/delete the record of books kept in the library. So we have the system into two parts : from user’s perspective and from admin’s .    Write code for storing books in order

**Comment by ishag8** [comment]
Isha Godse

**Comment by ishag8** [comment]
Please assign me this issue
Isha Godse

**Comment by Anjali2312-Thombare** [comment]
Anjali Thombare 
I would like to work on this issue

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, Could you assign this issue to me?

**Comment by RutujaKande** [comment]
@ishag8 your deadline is over

**Comment by ArtiHere** [comment]
@RutujaKande , I am done with my pervious work, can you assign this issue to me?

**Comment by Orange-5** [comment]
@ArtiHere and @Anjali2312-Thombare have already been assigned an issue. You can work only on 1 issue at a time. Once you complete you may work on this issue if no one else comments on it
