### ISSUE TITLE
Addy builder needs help!

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#88]
"Addy was a builder at heart. He loved constructing new structures and making things with his own hands. One day, he was given a challenge by a group of builders. They wanted to see if he could construct the largest square using X identical squares, each with a side length of Y units.
Addy was excited about the challenge and immediately got to work. But as he started constructing, he realized that there was a rule he had to follow. The squares could not overlap with each other. This made the task much more challenging.
Addy tried many different combinations, but nothing seemed to work. He was starting to get frustrated when he remembered that he could always ask for help. That's when he decided to reach out to you.
Can you help Addy find the maximum area that can be achieved in constructing the largest square using the X identical squares, each with a side length of Y units, without any overlap?
Input Format
The first line of input contains a single integer T denoting the number of test cases. The description of T test cases follows:
The first and only line of each test case contains two space-separated integers X,Y."

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, Could you assign this issue to me?

**Comment by RutujaKande** [comment]
@ArtiHere your deadline is over and also the requirement was code for the problem.
