### ISSUE TITLE
Find the minimum number which when added to  given array, makes all numbers >0

### ISSUE THREAD

**Issue by ananahyeah** [Mozilla-Campus-Club-Cummins/Spring-of-Code#9]
Write a program to find the number that converts all numbers in the given array to positive(>0) 
Note: (0 is not allowed in the projected answer array) 
Fixed input :
array i [6]={ -14, 23, 0, 5, -10, -1}

**Comment by Sannidhi26** [comment]
Sannidhi Nandgaonkar 
SY Comp
I have completed my first issue . can you please assign me this issue?

**Comment by PiyushaGhodake** [comment]
@ananahyeah I would like to work on this issue.
Piyusha Ghodake.
