### ISSUE TITLE
blog about social media influence

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#90]
We all have spent our daily time on social media.There are many good influences and also many bad.Write your views describing both sides.

**Comment by Sannidhi26** [comment]
I would like to work on this problem statement
Sannidhi Nandgaonkar
Sy comp

**Comment by RutujaKande** [comment]
You are already assigned with 1 issue so you can work on this after you
complete with previous one

**Comment by Sannidhi26** [comment]
I am sannidhi nandgaonkar
I would like to work on this issue.

**Comment by Orange-5** [comment]
@Sannidhi26 you are assigned to this issue.
