### ISSUE TITLE
Blog about college life

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#91]
Write about the ups and down of your college life and describe how its going so far.

**Comment by sayli2003** [comment]
I would like to work on this issue
Sayli Borole
Sy comp

**Comment by RutujaKande** [comment]
@sayli2003  you can work on this after you complete your first issue

**Comment by RutujaKande** [comment]
@sayli2003 now you can work on this issue
