### ISSUE TITLE
Documentation about graph data structure

### ISSUE THREAD

**Issue by RutujaKande** [Mozilla-Campus-Club-Cummins/Spring-of-Code#92]
documentation about graph data structure

**Comment by janhavipunse** [comment]
Janhavi Punse
SY COMPUTER
UCE2021458
I would like to work on this

**Comment by RutujaKande** [comment]
Janhavi now you can work on this issue as your first issue is completed

**Comment by RutujaKande** [comment]
@janhavipunse as you were assigned this issue but you haven't come with solution till deadline so I am unassigning you,but you can try other issue

**Comment by janhavipunse** [comment]
Di I have uploaded it already

**Comment by RutujaKande** [comment]
Kaha pe kiya, merko visible nhi he

**Comment by janhavipunse** [comment]
Solutions folder mai ,PR hai meri solution of issue #92 naam ka
