### ISSUE TITLE
Product Landing Page 

### ISSUE THREAD

**Issue by vaishh29** [Mozilla-Campus-Club-Cummins/Spring-of-Code#93]
Create a Product landing page for a product/service using HTML, CSS and Image editing . 

The goal of a Landing page is to appeal to a consumer to take action with respect to the product. The actions that a visitor takes on a landing page is what determines an advertiser's conversion rate.
It should be simple with minimal product information wherein the focus should lie on the design .

**Comment by IshwariTate** [comment]
Ishwari Tate 
TY
Cummins College of Engineering,Pune 
I would like to work on this issue

**Comment by vaishh29** [comment]
> Ishwari Tate TY Cummins College of Engineering,Pune I would like to work on this issue

You can start working on the issue. You have 2days for completion.

**Comment by Prachi-0704** [comment]
Prachi Patil
SY ENTC
I would like to work on this issue.

**Comment by vaishh29** [comment]
> Prachi Patil SY ENTC I would like to work on this issue.

Please complete previous issue assigned. You can work on only one issue at a time.
Comment on this issue after its completion.

**Comment by ShreyaShetty263** [comment]
Shreya Shetty
would like to work on this issue

**Comment by vaishh29** [comment]
> Shreya Shetty would like to work on this issue

Please register for Spring of Code through the registration link in the mail.
Do comment again once done. I'll assign you the issue
