### ISSUE TITLE
Travel Website

### ISSUE THREAD

**Issue by Gaurika-Gupta** [Mozilla-Campus-Club-Cummins/Spring-of-Code#95]
Make a website using flexbox and grids describing various Travel locations a tourist can visit to. On clicking the respective location tab, the tourist should be directed to a web-page of that location.

The navigation bar should remain fixed on top of every web-page.

**Comment by alwaystanaya20** [comment]
Name- Vaibhavi Thakare
SY COMP

I'd like to work on this problem statement

**Comment by Gaurika-Gupta** [comment]
Hello Vaibhavi, You can create a pull request for this issue on or before 23rd March. While creating the request, you need to add the issue number in the Title. 
Assigning this issue to you.

**Comment by Gaurika-Gupta** [comment]
Unassigning you this issue as you couldnt complete the problem statement in the required time.

**Comment by ArtiHere** [comment]
I am Arti Tambade, TY IT
I would like to work on this issue, could you please assign this issue to me?
