### ISSUE TITLE
Web Application of a Multiplayer Game

### ISSUE THREAD

**Issue by Gaurika-Gupta** [Mozilla-Campus-Club-Cummins/Spring-of-Code#96]
Design a web based multi-player game which has a timer and keeps track of score.

**Comment by spoorti016** [comment]
Spoorti Aparanji
TY Comp 
I would like to work on this project
doubt-(do I have to build the whole game in 2 days or can I push the amount of work done till 2 days?)

**Comment by Gaurika-Gupta** [comment]
Yes you can work on this issue. You can make a request till 25th Night. 
You need to complete the whole problem statement.

**Comment by Gaurika-Gupta** [comment]
Assigning you this issue because you didn't make a pull request in the given time.
