### ISSUE TITLE
Machine Learning Regression Model

### ISSUE THREAD

**Issue by Gaurika-Gupta** [Mozilla-Campus-Club-Cummins/Spring-of-Code#98]
Download the boston house price prediction dataset and do the following-
-> Cleaning the dataset
-> Visualizing various features of the dataset (Using seaborn or matplotlib) 
-> Design a supervised learning regression model.

**Comment by kasturimandlik** [comment]
Kasturi Mandlik
I would ;like to work on this issue.

**Comment by Gaurika-Gupta** [comment]
Hello Kasturi, You can create a pull request for this issue on or before 22rd March. While creating the request, you need to add the issue number in the Title.
Assigning this issue to you.

**Comment by Gaurika-Gupta** [comment]
Please register for Spring of Codes first (Link has been shared via mail) and then I will assign you the issue.

**Comment by Rasika-Kanitkar** [comment]
I would love to participate in the project 
Rasika Kanitkar
SY Comp (UCE2021630)
I have also registered but through college email id

**Comment by aditisinghal1210** [comment]
I would like to participate in this project-Aditi Singhal,I have registered.

**Comment by Gaurika-Gupta** [comment]
@aarushichopkar You can work on this issue as no other issue is assigned to you. 
Make a pull request till 23rd Night and add the issue number while creating the pull request.
Assigning the issue to you.

**Comment by aarushichopkar** [comment]
Yes, thank you!!

**Comment by Sanskruti21-2002** [comment]
Sanskruti Wakode from SY Comp 
I would like to Work on this issue

**Comment by Gaurika-Gupta** [comment]
@aarushichopkar Unassigning you this issue as you could create a pull request in the desired time.

**Comment by Gaurika-Gupta** [comment]
> Wakode

I can not assign you an issue until the previous issue merges. Please let me know once its merged.

**Comment by kasturimandlik** [comment]
@Gaurika-Gupta Can you please assign me this issue?

**Comment by Auroraaa17** [comment]
I'd love to work on this issue

**Comment by sayli2003** [comment]
Sayli Borole
SY COMP
I would like to work on this issue
