### ISSUE TITLE
Background Generator

### ISSUE THREAD

**Issue by vaishh29** [Mozilla-Campus-Club-Cummins/Spring-of-Code#99]
Design a basic background or gradient color generator using HTML, CSS and JavaScript, where you will choose a color from the palette and that color will become the background.

**Comment by Rasika-Kanitkar** [comment]
I would love to work on this
Rasika Kanitkar
SY Comp (UCE2021630)

**Comment by vaishh29** [comment]
@Rasika-Kanitkar you can start working on the issue. You have 2days to complete it.

**Comment by Rasika-Kanitkar** [comment]
are any changes required?

**Comment by vaishh29** [comment]
> are any changes required?

no changes are required.

**Comment by vaishh29** [comment]
> Then , why merge is not happening?I have to start with other problem statement as well!because only 2 days were given for one problem right?

I have merged the request you can now work on another request

**Comment by Rasika-Kanitkar** [comment]
Thank u!
